version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: sudo npm install markdown-pdf
      - run: markdown-pdf -o CV.pdf ./README.md
      - store_artifacts:
          path: ./CV.pdf
          destination: CV.pdf
