version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: apt install -y nodejs-legacy fonts-ipafont-gothic
      - run: sudo npm install -g markdown-pdf
      - run: wget https://gist.githubusercontent.com/andyferra/2554919/raw/10ce87fe71b23216e3075d5648b8b9e56f7758e1/github.css
      - run: markdown-pdf -g github.css -o CV.pdf ./README.md
      - store_artifacts:
          path: ./CV.pdf
          destination: CV.pdf
